# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Eyepetizer' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire'
  pod 'Moya'
  pod 'SwiftyJSON'
  pod 'HandyJSON', '~>4.0.0-beta.1'
  pod 'Kingfisher'
  pod 'IBAnimatable'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'MJRefresh'
  pod 'SGPagingView'
  pod 'FDFullscreenPopGesture', '1.1'
  pod 'SnapKit', '~> 4.0.0'

  # Pods for Eyepetizer

end
